{ config, lib, pkgs, ... }:
let
  lanzaboote-src = pkgs.fetchFromGitHub {
    owner = "nix-community";
    repo = "lanzaboote";
    rev = "v0.4.1"; # Replace with the version you want
    sha256 = "0l82cq5xjbbh8grfvzz49qf3g2b1wrpnpfv1jdjyxwfj0n9a0n1j"; # Replace with the correct hash
  };

  lanzaboote = import lanzaboote-src;
in
{
#   imports = [
#     lanzaboote.nixosModules.lanzaboote
#   ];

    environment.systemPackages = [
    # For debugging and troubleshooting Secure Boot.
    pkgs.sbctl
  ];

  # Lanzaboote currently replaces the systemd-boot module.
  # This setting is usually set to true in configuration.nix
  # generated at installation time. So we force it to false
  # for now.
  # boot.loader.systemd-boot.enable = lib.mkForce boot.lanzaboote = {
  #   enable = true;
  #   pkiBundle = "/etc/secureboot";
  # # (generated by running 'sudo sbctl create-keys' before)
  # };

  # boot.bootspec.enableValidation = true;
}
